/**
 *	@file QuestionBlock.hpp
 *	@author Matteo Loporchio
 *
 *	@brief Implementation of the QuestionBlock class
 */

#include <ctime>
#include "QuestionBlock.hpp"
#include "SuperMushroom.hpp"
#include "OneUpMushroom.hpp"
#include "CoinPowerup.hpp"
#include "Textures.hpp"
#include "Physics.hpp"

/**
 *	@brief QuestionBlock constructor
 *
 *	@param x initial position along the x axis
 *	@param y initial position along the y axis
 *	@param id identifier of the powerup generated by the QuestionBlock
 *	@param textures_ vector of textures to use for the QuestionBlock
 */
QuestionBlock::QuestionBlock(float x, float y, powerup_t id, std::vector<sf::Texture> &textures_) :
	Block(QUESTION, x, y, textures_[0]),
	textures(textures_),
	elapsed(0),
	textureID(ACTIVE_0),
	hasPowerup(true),
	spawn(id)
{
	// These are automatically set:
	// this -> active = true;
	// this -> collidable = true;
}

/**
 *	@brief Called when the QuestionBlock is hit
 */
void QuestionBlock::hit() {
	if (this -> active) {
		this -> active = false;
		this -> sprite.setTexture(textures[(int) INACTIVE]);
	}
}

/**
 *	@brief Returns the powerup produced by the QuestionBlock
 *
 *	@return pointer to the new Powerup object
 */
Powerup *QuestionBlock::getPowerup() {
	if (this -> hasPowerup) {
		Powerup *p = NULL;
		bool loadResult = false;
		sf::Vector2f pos = this -> getPosition();
		switch (this -> spawn) {
			case SUPER_MUSHROOM: {
				// Obtain the position of the current block.
				sf::Texture *t = new sf::Texture();
				loadResult = t -> loadFromFile(SUPERMUSHROOM_TEXTURE);
				if (!loadResult) throw std::runtime_error("getPowerup: Cannot load super mushroom texture.");
				SuperMushroom *m = new SuperMushroom(pos.x, pos.y - SIZE, *t);
				p = (Powerup *) m;
			}; break;
			case ONEUP_MUSHROOM: {
				sf::Texture *t = new sf::Texture();
				loadResult = t -> loadFromFile(ONEUPMUSHROOM_TEXTURE);
				if (!loadResult) throw std::runtime_error("getPowerup: Cannot load one-up mushroom texture.");
				OneUpMushroom *o = new OneUpMushroom(pos.x, pos.y - SIZE, *t);
				p = (Powerup *) o;
			}; break;
			case COIN_POWERUP: {
				sf::Texture *t = new sf::Texture();
				loadResult = t -> loadFromFile(COIN_POWERUP_TEXTURE);
				if (!loadResult) throw std::runtime_error("getPowerup: Cannot load coin texture.");
				CoinPowerup *c = new CoinPowerup(pos.x, pos.y - SIZE, *t);
				p = (Powerup *) c;
			}; break;
			default: break;
		}
		this -> hasPowerup = false;
		return p;
	}
	return NULL;
}

/**
 *	@brief Update function for the QuestionBlock object
 *
 *	@param dt time elapsed since last update
 */
void QuestionBlock::update(sf::Time dt) {
	if (this -> active) {
		textureID = nextQuestionTexture(textureID);
		this -> sprite.setTexture(textures[(int) textureID]);
	}
}
