/**
 *	@file Scene.hpp
 *	@author Matteo Loporchio
 *
 *	@brief Definition of the Scene class
 */

#ifndef SCENE_H
#define SCENE_H

#include <SFML/Window.hpp>
#include <SFML/Graphics.hpp>
#include <random>
#include <cstdio>
#include <vector>
#include "Config.hpp"
#include "Mario.hpp"
#include "Enemy.hpp"
#include "Powerup.hpp"
#include "Layer.hpp"
#include "Tilemap.hpp"

/** Maximum value of an integer generated by std::uniform_int_distribution. */
#define MAX_RANDOM_VALUE 100000

/** Initial text for the score label. */
#define SCORE_INIT_MSG "Score: 0"

/** Initial position for the score label. */
#define SCORE_POSITION sf::Vector2f(16.f, 16.f)

/** Font size for the score label. */
#define SCORE_FONT_SIZE 12

/** Game over message. */
#define GAME_OVER_MSG "Game over!"

/** Font size for the game over label. */
#define GAME_OVER_FONT_SIZE 20

/** Win message. */
#define WIN_MSG "Level complete!"

/** Font size for the win label. */
#define WIN_FONT_SIZE 20

/** Info message. */
#define INFO_MSG "Press ENTER to continue"

/** Font size for the info label. */
#define INFO_FONT_SIZE 12

/** Time elapsed between two textures for dynamic blocks. */
#define BLOCK_ANIMATION_TIME 100

class Scene {
	private:
		Layer fg;
		Layer bg;
		sf::Texture bgImage;
		sf::Sprite bgSprite;
		sf::Font font;
		sf::Text scoreLabel;
		sf::Text gameOverLabel;
		sf::Text winLabel;
		sf::Text infoLabel;
    	std::default_random_engine random_engine;
		std::uniform_int_distribution<int> uniform_dist;
		std::vector<sf::Texture> staticTextures;
		std::vector<sf::Texture> questionTextures;
		std::vector<sf::Texture> coinTextures;
		std::vector<sf::Texture> goombaTextures;
		std::vector<sf::Texture> piranhaPlantTextures;
		std::vector<sf::Texture> koopaTextures;
		std::vector<Block *> blocks;
		std::vector<Block *> currentBlocks;
		std::vector<Enemy *> enemies;
		std::vector<Enemy *> currentEnemies;
		std::vector<Powerup *> powerups;
		sf::Music theme;
		sf::SoundBuffer sceneSoundBufferWin;
		sf::Sound sceneSoundWin;
		Tilemap tilemap;
		sf::Clock timer;
		Mario hero;
		bool win;
		bool gameOver;
		void loadTextures();
		void processTilemap();
		void updateBlocks(sf::Time dt);
		void updateEnemies(sf::Time dt);
		void updatePowerups(sf::Time dt);
		void updateLabels();
		void updateLayers(sf::Vector2f p);
		void refreshCurrentBlocks();
		void refreshCurrentEnemies();
		bool checkPlayerDead();
		bool checkPlayerWin();
	public:
		Scene(const std::string &path);
		~Scene();
		void handleEvent(sf::Event e, game_mode_t &gameMode);
		void updateScene();
		void drawScene(sf::RenderWindow &window);
		int getSceneWidth();
		int getSceneHeight();
};

#endif
